spring:
  datasource:
    url: jdbc:mysql://localhost:3306/example_db?serverTimezone=Mexico/General
    username: root
    password: P@ssw0rd

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect