server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/example_db
    username: postgres
    password: P@ssw0rd

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect